name: python_ping_test
label: Docker Python Example with Custom Image
description: An example docker skillet that executes a python script found in the same directory using a custom image

type: docker

labels:
  collection: Example Skillets

variables:
  - name: input_type
    description: select to use entered list or file input for the ping targets
    default: list
    type_hint: dropdown
    dd_list:
      - key: file
        value: file
      - key: list
        value: list

  - name: url_list
    description: list of URLs or IPs to ping
    default: []
    type_hint: list
    toggle_hint:
      source: input_type
      value: list

  - name: file_name
    description: file with target ping list
    default: some_file.txt
    type_hint: file
    toggle_hint:
      source: input_type
      value: file

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: python_test
    image: nembery/url_ping
    cmd: python3 ./ping_test.py
