name: all_variables
# label used for menu selection
label: All Variable Types

description: |
  This skillet has all defined varialble types for testing

# type of skillet (panos or panorama or template or terraform)
type: panos

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: Broken Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: GARBAGE
  - name: DISABLED
    description: No Bueno
    default: panos-01
    type_hint: disabled
  - name: ip_address
    description: IP Address
    default: 0.0.0.0
    type_hint: ip_address
  - name: true_false
    description: True False
    default: True
    type_hint: dropdown
    dd_list:
      - key: true
        value: True
      - key: false
        value: False
  - name: yes_no
    description: Yes No
    default: 'No'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'Yes'
      - key: 'no'
        value: 'No'


# Snippets is an ordered list of configuration xml fragments that will be pushed to the Pan-OS NGFW. The xpath
# determines where in the configuration heirarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: device_system
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system.xml