name: python_broken_inputs
# label used for menu selection
label: Broken Python example

description: |
  This skillet uses a textarea for python inputs

# type of skillet (panos or panorama or template or terraform)
type: python3

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection:
    - Broken Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text
  - name: test_var
    description: Some input
    default: some input\nwith more stuff\nand more stuff
    type_hint: text_area


# Snippets is an ordered list of configuration xml fragments that will be pushed to the Pan-OS NGFW. The xpath
# determines where in the configuration heirarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: script
    file: python_test.py