name: dynamic_dropdown_debug
# label used for menu selection
label: Show captured List in dropdown

description: |
  This skillet demonstrates a simple template to show captured list values

# type of skillet (panos or panorama or template or terraform)
type: template

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: Rest Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: hostname
    description: Hostname
    default: not-saved
    type_hint: text
  - name: uptime
    description: Uptime
    default: not-saved
    type_hint: text
  - name: sw_version
    description: Software Version
    default: not-saved
    type_hint: text
  - name: selected_interface
    description: Interface
    default: not-saved
    type_hint: dropdown
    source: interface_names


# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: debug_output
    file: output.j2
