name: hostname_change_textarea
# label used for menu selectio
label: Hello World Example (Set hostname) with textarea

description: |
  This skillet uses a textarea

# type of skillet (panos or panorama or template or terraform)
type: template

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection:
    - Broken Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text
  - name: test_var
    description: Firewall description
    default:
    type_hint: textarea


# Snippets is an ordered list of configuration xml fragments that will be pushed to the Pan-OS NGFW. The xpath
# determines where in the configuration heirarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: device_system
    file: device_system.xml