name: workflow_ng
label: Simple Workflow Example with Custom code

description: |
  This skillet demonstrates a simple workflow consisting of 3 steps, each step modifies the workflow

# type of skillet (panos or panorama or template or terraform)
type: workflow

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: Rest Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: cert_name
    description: Certificate name
    default: CACert
    type_hint: text


# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: generate_api_key
    pre_processor: step1_pre.py
    form_validator: step1_validator.py
    post_processor: step1.py
  - name: get_system_info
    post_processor: step2.py
  - name: get_system_info_debug
    post_processor: step3.py



