name: workflow_ng
label: Simple Workflow Example with Custom code

description: |
  This skillet demonstrates a simple workflow consisting of 3 steps, each step modifies the workflow

# type of skillet (panos or panorama or template or terraform)
type: workflow

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: Rest Skillets

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: cert_name
    description: Certificate name
    default: CACert
    type_hint: text


# workflow snippets call other Skillets but they have the opportunity to modify the skillet variables and workflow
# during 3 phases#
# pre_processor gets called before the form is rendered
# form_validator gets called after the form is submitted but before any action is taken
# post_processor gets called after the form is submitted and after the skillet action is performed
snippets:
  - name: generate_api_key
    pre_processor: step1_pre.py
    form_validator: step1_validator.py
    post_processor: step1_post.py
  - name: get_system_info
    post_processor: step2.py
  - name: get_system_info_debug
    post_processor: step3.py



