name: validate-something-06FA23C1-BB8C-407D-B61A-B0FB8D89180E
label: Validate Some Stuff

description: |
  This skillet does a basic validation

type: pan_validation
labels:
  collection: Experimental Skillets

variables:
  - name: FW_NAME
    description: Some Parameter
    default: yes
    type_hint: text

snippets:
  - name: show_device_system
    cmd: show
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    outputs:
      # capture all the xml elements found at the 'update-schedule' xpath and convert it into a python object
      - name: update_schedule_object
        capture_object: update-schedule
  - name: update_schedule_configured
    label: Ensure Update Schedules are Configured
    cmd: validate
    # test to determine if update-schedule is configured
    test: update_schedule_object is none
    # if the test is TRUE, then return this message, doc link, and severity
    documentation_link: https://iron-skillet.readthedocs.io
    severity: medium
  - name: update_schedule_stats_service_configured
    label: Ensure Statistics Service is enabled
    cmd: validate
    # test to see if the update-schedule does NOT have a child element with the name 'statistics-service'
    test: update_schedule_object|missing_config('statistics-service')
    # if the test is TRUE, then return this information
    documentation_link: https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-new-features/content-inspection-features/telemetry-and-threat-intelligence-sharing
    severity: medium
    # only run this test when update_schedule is actually configured
    when: update_schedule_object is not none
  - name: ensure_wildfire_check_1_min
    label: Ensure Wildfire Checks every 1 minute
    cmd: validate
    # test to see if the update-schedule does NOT have a child element with the name 'statistics-service'
    test: |
      (update_schedule_object['update-schedule']['wildfire'] is not none and
      update_schedule_object['update-schedule']['wildfire']['recurring'] is not none and
      update_schedule_object['update-schedule']['wildfire']['recurring']['every-min'] is not none)
    # if the test is TRUE, then return this information
    documentation_link: https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-new-features/content-inspection-features/telemetry-and-threat-intelligence-sharing
    severity: medium
    # only run this test when update_schedule is actually configured
    when: update_schedule_object is not none
