name: hostname_change
label: Hello World Example (Set hostname)

description: |
  This skillet demonstrates a very basic Pan-OS configuration change. This allows the user to configure the
  hostname on a PAN-OS NGFW

type: panos
labels:
  collection: Example Skillets

variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text

snippets:
  - name: check_hostname
    cmd: op
    cmd_str: <show><system><info></info></system></show>
    outputs:
      - name: hostname
        capture_pattern: result/system/hostname
  - name: set_hostname
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system.xml
    when: hostname != FW_NAME