name: workflow_test_capture_multi
label: Workflow Test With Multi Lists
description: Another Simple test of the workflow system
type: workflow
labels:
  collection:
    - Example Skillets

variables:
  - name: TARGET_IP
    description: Host
    default: 0.0.0.0
    type_hint: fqdn_or_ip
  - name: TARGET_PORT
    description: Port
    default: 443
    type_hint: number
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

snippets:
  - name: output_capture_examples_5FC6B908-9F44-4CEE-829B-72F2B8B11D27
  - name: dynamic_dropdown_again_3299DE05-78E5-498B-A959-B07FC78594D
