name: output_capture_examples_812E106E-EF84-48CC-A2CB-96F9D7DA7295

label: Output Capturing from a PAN-OS Device

description: |
  This skillet demonstrates how to capture lists of values from a PAN-OS Device. This includes from op commands,
  set commands and command completions to get things like available zone names, options, etc.

type: rest

labels:
  collection:
    - Example Skillets

variables:
  - name: TARGET_IP
    description: Host
    default: 0.0.0.0
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key

  - name: completion
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry
      [@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group&key={{ api_key }}
    output_type: xml
    outputs:
      - name: profile_groups
        capture_pattern: ./completions/completion

  - name: zones
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/entry
      [@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone&key={{ api_key }}
    output_type: xml
    outputs:
      - name: all_zones
        capture_pattern: ./completions/completion//@value

  - name: interfaces
    path: https://{{ TARGET_IP }}/api/?type=op&cmd=<show><interface>logical</interface></show>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: interface_names
        capture_pattern: ./result/ifnet/entry/name


